Ensure that punchblock uses .WAV extension for wav49 format
adhearsion/punchblock pull request #259
Opened 2016-10-13 21:30 UTC by system123

Ensures that the uri returned when wav49 format is used, has the same file extension as what asterisk will use.

2016-10-13 21:32 UTC, benlangfeld commented
Does asterisk never produce .wav49? Is this documented anywhere?

2016-10-13 21:34 UTC, system123 commented
See the related issue: https://github.com/adhearsion/punchblock/issues/258

Asterisk hardcodes the same extension replacement.

2016-10-13 21:40 UTC, bklang commented
I'm pretty sure the correct replacement is `WAV`,  case-sensitive. Did you test this with a real app yet? Also, could we get a spec to cover this behavior?

2016-10-13 21:43 UTC, system123 commented
@bklang you are correct, I'll fix that. It should be .WAV I'll also write a spec.

2016-10-13 22:06 UTC, system123 commented
Ok changes are now correct, and spec is passing.

2016-10-13 22:11 UTC, bklang requested changes

2016-10-13 22:11 UTC, bklang commented on lib/punchblock/translator/asterisk/component/record.rb
> +            uri = "file://#{filename}.#{@format}".gsub('wav49', 'WAV')
One more it: to be safe, the `gsub` really should only be applied to `@format` and not the entire filename

2016-10-13 22:24 UTC, system123 commented on lib/punchblock/translator/asterisk/component/record.rb
> +            uri = "file://#{filename}.#{@format}".gsub('wav49', 'WAV')
Made the change

2016-10-13 22:26 UTC, bklang approved these changes

2016-10-14 12:07 UTC, benlangfeld requested changes
Could we get an entry in the changelog also before merging this?

2016-10-18 10:22 UTC, merged

2016-10-18 10:23 UTC, benlangfeld commented
Thanks Lloyd. Would you perhaps prep this against Adhearsion 2, which merges Punchblock?